### ISSUE TITLE
Show status of recent build(s) in UI

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#1]
Let's use the CircleCI API to get the status of the most recent build or list of builds on the master branch.
https://circleci.com/docs/api/#recent-builds-for-a-single-project

**Comment by jmolivas** [comment]
Fixed with https://github.com/octahedroid/wp-build-hooks/pull/3

![image](https://user-images.githubusercontent.com/366275/78730693-70510c80-78f2-11ea-8f14-a6481c0349e6.png)
