### ISSUE TITLE
Use CircleCI API version 2 for triggering builds

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#14]
CircleCI is ending the ability to trigger jobs through the v1.1. API. https://circleci.com/blog/a-deprecation-notice-on-job-triggering-with-api-v1-1/

@jmolivas I know we talked about this at some point and I think you had a reason to stick with 1.1. But I just tried triggering a "pipeline via the version 2 API and it seemed to work fine. That seems like the safer API to build on: https://circleci.com/docs/api/v2/#circleci-api-pipeline

**Comment by jmolivas** [comment]
@stevector Sure we will take care of updating this

**Comment by jmolivas** [comment]
Fixed with https://github.com/octahedroid/wp-build-hooks/pull/18
