### ISSUE TITLE
Add php_Codesniffer with WP Coding Standards

### ISSUE THREAD

**Issue by omero** [octahedroid/wp-build-hooks#16]
We need to configure `phpcs` using the [WP Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards) 

We can take inspiration on how is managed these utilities on the [wp-graphql](https://github.com/wp-graphql/wp-graphql) plugin

**Comment by jardix22** [comment]
Pull request #41 

**Steps to validate:**
- Install dependencies `composer install`
- Run composer _phpcs_ script `composer run-script phpcs`
- Run composer _phpcbf_ script `composer run-script phpcbf`
- To remove the development dependencies run  `composer install --no-dev`

**Comment by jmolivas** [comment]
Fixed with Fixed with 
https://github.com/octahedroid/wp-build-hooks/pull/40 and https://github.com/octahedroid/wp-build-hooks/pull/41
