### ISSUE TITLE
Add a UI option for setting CircleCI token

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#2]
I think we saw yesterday that reliance on the Terminus Secrets Plugin can slow down someone installing this plugin.

I still think it makes sense to store the token in an unversioned json file, but let's try writing that file through the UI. Maybe name it `secrets.wp-build-hooks.json`

**Comment by jmolivas** [comment]
Fixed with https://github.com/octahedroid/wp-build-hooks/pull/3/files

![image](https://user-images.githubusercontent.com/366275/78730647-4ac40300-78f2-11ea-9e1e-699e78c1b8be.png)


We used `wp-content/uploads/private/secrets.json` instead and replace values keeping any other values on the file
