### ISSUE TITLE
Security of secret JSON file

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#22]
Right now this plugin is using a private json file to store the CircleCI API key. That's more secure than putting it in the database or in version control but we're relying on the private files directory being protected to prevent it from being read publicly. I don't think other hosts have that convention. The default behavior when not on Pantheon might need to be to store the API key in the database.

This task isn't critical right now when all sites using the plugin are on Pantheon, but this should block adding the plugin to the WordPress plugin directory.

**Comment by jmolivas** [comment]
Fixed with https://github.com/octahedroid/wp-build-hooks/pull/26

**Comment by jmolivas** [comment]
@stevector Should we allow user to use wp-options via a configuration maybe a checkbox even when running on pantheon?

**Comment by stevector** [comment]
@jmolivas No, I'd prefer to minimize configuration options.
