### ISSUE TITLE
allow full url as input format for repo

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#23]
The last two people we've walked through setting up this plugin have tried copying the full repo URL (`https://github.com/user-name/repo-name`) rather than the format CircleCI wants (`github/user-name/repo-name`). I think we should allow either.

This need might also be an opportunity to start adding automated tests. If we have a function that breaks the user input string into the usable subcomponents (git provider, username, repo name) then that is a very unit-test element.

**Comment by jmolivas** [comment]
Fixed with https://github.com/octahedroid/wp-build-hooks/pull/25
