### ISSUE TITLE
make pantheonsite url scheme configurable

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#46]
Right now the plugin presumes sites are hosted on domains from `pantheonsite.io` https://github.com/octahedroid/wp-build-hooks/blob/master/wp-build-hooks.php#L400

That'll be a problem for sites like https://live--wpcampus-gatsby.my.pantheonfrontend.website/

**Comment by jmolivas** [comment]
@stevector Do we want to support arbitrary domain names? I mean should we add an input text-field to allow the user add any data.

**Comment by stevector** [comment]
I don't know, we also have to accommodate the difference between the double dash separating used with  https://live--wpcampus-gatsby.my.pantheonfrontend.website/ and the single dash used on `pantheonsite`.

**Comment by jmolivas** [comment]
Fixed with PR: https://github.com/octahedroid/wp-build-hooks/pull/47

**Comment by jmolivas** [comment]
We still need to validate what are we going to do if no domain is entered.

Should we allow this?
If yes, should we disable the buttons
![image](https://user-images.githubusercontent.com/366275/82487428-2d5a8b00-9a93-11ea-8f63-47dec70abcc4.png)
