### ISSUE TITLE
Consider separate option for Pantheon Orb

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#48]
I think at this point our CircleCI configuration is pretty pantheon-specific. Should we break out a separate option here for CircleCI + Pantheon Orb? https://github.com/octahedroid/wp-build-hooks/blob/master/wp-build-hooks.php#L16

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/octahedroid/wp-build-hooks/pull/50
