### ISSUE TITLE
Test form with bad data

### ISSUE THREAD

**Issue by stevector** [octahedroid/wp-build-hooks#5]
When incorrect values are added for `job` or `repo`, a PHP error is shown that includes the full CircleCI token.

**Comment by jmolivas** [comment]
Add a try/catch to `trigger_build` function 
https://github.com/octahedroid/wp-build-hooks/blob/master/wp-build-hooks.php#L515-L519

**Comment by jmolivas** [comment]
Fixed with https://github.com/octahedroid/wp-build-hooks/pull/9
